export const Users=[
    {
        name:'Niv',
        score:375
    },
    {
        name:'Adar',
        score:285
    },
    {
        name:'Kiwi',
        score:175
    },
    {
        name:'Milki',
        score:315
    },
    {
        name:'Libi',
        score:75
    }
    
]
export const Questions = [
    {
        question:'Who is the vocalist on "Let It Be"?',
        optionA:'John Lennon',
        optionB:'Ringo Starr',
        optionC:'Paul McCartney',
        optionD:'George Harrison',
        answer:'optionC',
    },
    {
        question: 'Which artist released the album "Thriller"?',
        optionA: 'Michael Jackson',
        optionB: 'Prince',
        optionC: 'Madonna',
        optionD: 'Elton John',
        answer: 'optionA',
    },
    {
        question: 'What year did The Beatles release their album "Sgt. Pepper\'s Lonely Hearts Club Band"?',
        optionA: '1965',
        optionB: '1967',
        optionC: '1969',
        optionD: '1971',
        answer: 'optionB',
    },
    {
        question: 'Who is known as the "Queen of Pop"?',
        optionA: 'Whitney Houston',
        optionB: 'Lady Gaga',
        optionC: 'Madonna',
        optionD: 'Beyoncé',
        answer: 'optionC',
    },
    {
        question: 'Which band is famous for the hit song "Bohemian Rhapsody"?',
        optionA: 'The Rolling Stones',
        optionB: 'Led Zeppelin',
        optionC: 'Queen',
        optionD: 'Pink Floyd',
        answer: 'optionC',
    },
    {
        question: 'What instrument is Yo-Yo Ma famous for playing?',
        optionA: 'Piano',
        optionB: 'Violin',
        optionC: 'Cello',
        optionD: 'Guitar',
        answer: 'optionC',
    },
    {
        question: 'Which song by Nirvana is considered one of the most iconic of the grunge era?',
        optionA: 'Smells Like Teen Spirit',
        optionB: 'Come As You Are',
        optionC: 'Lithium',
        optionD: 'Heart-Shaped Box',
        answer: 'optionA',
    },
    {
        question: 'Who wrote the classical piece "Clair de Lune"?',
        optionA: 'Ludwig van Beethoven',
        optionB: 'Claude Debussy',
        optionC: 'Johann Sebastian Bach',
        optionD: 'Wolfgang Amadeus Mozart',
        answer: 'optionB',
    },
    {
        question: 'What genre is the band The Chemical Brothers primarily known for?',
        optionA: 'Rock',
        optionB: 'Electronic',
        optionC: 'Jazz',
        optionD: 'Hip Hop',
        answer: 'optionB',
    },
    {
        question: 'Which singer is known for the hit single "Rolling in the Deep"?',
        optionA: 'Adele',
        optionB: 'Taylor Swift',
        optionC: 'Katy Perry',
        optionD: 'Rihanna',
        answer: 'optionA',
    },
    {
        question: 'In which city did the punk rock movement originate in the 1970s?',
        optionA: 'New York City',
        optionB: 'London',
        optionC: 'Los Angeles',
        optionD: 'Detroit',
        answer: 'optionB',
    },
    {
        question: 'Which legendary musician is known for the song "Purple Haze"?',
        optionA: 'Jimi Hendrix',
        optionB: 'Jim Morrison',
        optionC: 'Eric Clapton',
        optionD: 'Carlos Santana',
        answer: 'optionA',
    },
    {
        question: 'What was Elvis Presley’s nickname?',
        optionA: 'The King of Rock and Roll',
        optionB: 'The King of Pop',
        optionC: 'The King of Blues',
        optionD: 'The King of Jazz',
        answer: 'optionA',
    },
    {
        question: 'Which song did Bob Dylan famously perform at the 1965 Newport Folk Festival?',
        optionA: 'Blowin\' in the Wind',
        optionB: 'Like a Rolling Stone',
        optionC: 'The Times They Are A-Changin\'',
        optionD: 'Mr. Tambourine Man',
        answer: 'optionB',
    },
    {
        question: 'Which classical composer was known as the "Red Priest"?',
        optionA: 'Antonio Vivaldi',
        optionB: 'Johann Pachelbel',
        optionC: 'George Frideric Handel',
        optionD: 'Franz Joseph Haydn',
        answer: 'optionA',
    },
    {
        question: 'What was the first music video played on MTV?',
        optionA: 'Thriller by Michael Jackson',
        optionB: 'Video Killed the Radio Star by The Buggles',
        optionC: 'Like a Virgin by Madonna',
        optionD: 'Sledgehammer by Peter Gabriel',
        answer: 'optionB',
    },
    {
        question: 'Which musical genre is associated with the artist Bob Marley?',
        optionA: 'Reggae',
        optionB: 'Ska',
        optionC: 'Rocksteady',
        optionD: 'Dancehall',
        answer: 'optionA',
    },
    {
        question: 'What is the name of the musical scale consisting of seven notes, including all the white keys on a piano?',
        optionA: 'Major Scale',
        optionB: 'Minor Scale',
        optionC: 'Chromatic Scale',
        optionD: 'C Major Scale',
        answer: 'optionD',
    },
    {
        question: 'Which artist released the song "Bad Guy" in 2019?',
        optionA: 'Billie Eilish',
        optionB: 'Ariana Grande',
        optionC: 'Dua Lipa',
        optionD: 'Khalid',
        answer: 'optionA',
    },
    {
        question: 'Which band recorded the album "Nevermind"?',
        optionA: 'Pearl Jam',
        optionB: 'Nirvana',
        optionC: 'Soundgarden',
        optionD: 'Alice in Chains',
        answer: 'optionB',
    },
    {
        question: 'Which famous music festival took place in 1969?',
        optionA: 'Coachella',
        optionB: 'Glastonbury',
        optionC: 'Woodstock',
        optionD: 'Lollapalooza',
        answer: 'optionC',
    },
    {
        question: 'Who is the artist behind the album "Born to Run"?',
        optionA: 'Bruce Springsteen',
        optionB: 'Bob Dylan',
        optionC: 'Neil Young',
        optionD: 'Tom Petty',
        answer: 'optionA',
    },
    {
        question: 'Which genre of music is characterized by a strong rhythmic beat and improvisation?',
        optionA: 'Classical',
        optionB: 'Jazz',
        optionC: 'Electronic',
        optionD: 'Country',
        answer: 'optionB',
    },
    {
        question: 'Which artist released the song "Uptown Funk"?',
        optionA: 'Bruno Mars',
        optionB: 'Pharrell Williams',
        optionC: 'Mark Ronson',
        optionD: 'Justin Timberlake',
        answer: 'optionA',
    },
    {
        question: 'Which composer is known for his "Symphony No. 5"?',
        optionA: 'Beethoven',
        optionB: 'Bach',
        optionC: 'Tchaikovsky',
        optionD: 'Mozart',
        answer: 'optionA',
    },
    {
        question: 'Which genre is known for its use of heavy guitar riffs and powerful vocals?',
        optionA: 'Country',
        optionB: 'Metal',
        optionC: 'Pop',
        optionD: 'R&B',
        answer: 'optionB',
    },
    {
        question: 'Which artist is known for the hit song "Poker Face"?',
        optionA: 'Lady Gaga',
        optionB: 'Katy Perry',
        optionC: 'Rihanna',
        optionD: 'Beyoncé',
        answer: 'optionA',
    },
    {
        question: 'Who was the lead singer of the band Led Zeppelin?',
        optionA: 'Robert Plant',
        optionB: 'Jimmy Page',
        optionC: 'John Paul Jones',
        optionD: 'John Bonham',
        answer: 'optionA',
    },
    {
        question: 'Which instrument is commonly associated with bluegrass music?',
        optionA: 'Banjo',
        optionB: 'Saxophone',
        optionC: 'Trumpet',
        optionD: 'Synthesizer',
        answer: 'optionA',
    },
    {
        question: 'Which artist is famous for the album "Rumours"?',
        optionA: 'Fleetwood Mac',
        optionB: 'The Eagles',
        optionC: 'The Rolling Stones',
        optionD: 'The Who',
        answer: 'optionA',
    },
    {
        question: 'Which composer wrote the "Four Seasons" violin concertos?',
        optionA: 'Antonio Vivaldi',
        optionB: 'Johann Sebastian Bach',
        optionC: 'Ludwig van Beethoven',
        optionD: 'Wolfgang Amadeus Mozart',
        answer: 'optionA',
    },
    {
        question: 'Which American singer is known for the hit single "I Will Always Love You"?',
        optionA: 'Whitney Houston',
        optionB: 'Mariah Carey',
        optionC: 'Celine Dion',
        optionD: 'Adele',
        answer: 'optionA',
    },
    {
        question: 'Which genre of music is often associated with the use of synthesizers and electronic beats?',
        optionA: 'Rock',
        optionB: 'Pop',
        optionC: 'Electronic',
        optionD: 'Blues',
        answer: 'optionC',
    },
    {
        question: 'Which band released the song "Sweet Child o’ Mine"?',
        optionA: 'Guns N’ Roses',
        optionB: 'Aerosmith',
        optionC: 'AC/DC',
        optionD: 'Def Leppard',
        answer: 'optionA',
    },
    {
        question: 'What is the name of the musical symbol that indicates a quiet volume?',
        optionA: 'Forte',
        optionB: 'Piano',
        optionC: 'Allegro',
        optionD: 'Legato',
        answer: 'optionB',
    },
    {
        question: 'Which 1980s song by Cyndi Lauper became an anthem for individuality and self-expression?',
        optionA: 'Girls Just Want to Have Fun',
        optionB: 'Time After Time',
        optionC: 'True Colors',
        optionD: 'She Bop',
        answer: 'optionA',
    }
];
